<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/NanairoWorkReportTool.Core/NanairoWorkReportTool.Core.csproj" />
    <ProjectReference Include="../../src/NanairoWorkReportTool.Infrastructure/NanairoWorkReportTool.Infrastructure.csproj" />
    <ProjectReference Include="../../src/NanairoWorkReportTool/NanairoWorkReportTool.csproj" />
  </ItemGroup>
</Project>
